swagger: "2.0"
info:
  description: "This is a sample server TimeTables Server."
  version: "1.0.0"
  title: "TimeTables Server"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "schedulestore.swagger.io"
basePath: "/v2"
tags:
- name: "schedule"
  description: "Everything about your Schedule"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to timeTables"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /schedule:
    post:
      tags:
      - "schedule"
      summary: "Add a new schedule"
      description: ""
      operationId: "addSchedule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Schedule that need to add the app"
        required: true
        schema:
          $ref: "#/definitions/Schedule"
      responses:
        405:
          description: "Invalid input"
    put:
      tags:
      - "schedule"
      summary: "Update an existing schedule"
      description: ""
      operationId: "updateSchedule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Schedule object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Schedule"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "schedule not found"
        405:
          description: "Validation exception"
    get:
      tags:
      - "schedule"
      summary: "get all an existing schedules"
      description: ""
      operationId: "getSchedules"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        404:
          description: "schedules not found"
        405:
          description: "Validation exception"

  /schedule/findByTags:
    get:
      tags:
      - "schedule"
      summary: "Finds Shedules by tags"
      description: "Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing."
      operationId: "findSchedulesByTags"
      produces:
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Tags to filter by"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Schedule"
        400:
          description: "Invalid tag value"
  /schedule/{scheduleId}:
    get:
      tags:
      - "schedule"
      summary: "Find schedule by ID"
      description: "Returns a single schedule"
      operationId: "getscheduleById"
      produces:
      - "application/json"
      parameters:
      - name: "scheduleId"
        in: "path"
        description: "ID of schedule to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Schedule"
        400:
          description: "Invalid ID supplied"
        404:
          description: "schedule not found"
    post:
      tags:
      - "schedule"
      summary: "Updates a schedule in the store with form data"
      description: ""
      operationId: "updatescheduleWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "scheduleId"
        in: "path"
        description: "ID of schedule that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "Updated name of the schedule"
        required: false
        type: "string"
      - name: "status"
        in: "formData"
        description: "Updated status of the schedule"
        required: false
        type: "string"
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "schedule"
      summary: "Deletes a schedule"
      description: ""
      operationId: "deleteschedule"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "scheduleId"
        in: "path"
        description: "schedule id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "schedule not found"
  
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
  /user/login:
    post:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /user/reserve/{numberSlot}:
    post:
      tags:
      - "reserve"
      summary: "reserve of free slot"
      description: ""
      operationId: "reserveOfSlot"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "numberSlot"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"
  /user/{userId}/reserve:
    get:
      tags:
      - "reserve"
      summary: "get all own slots"
      description: ""
      operationId: "getSlots"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"     
  /user/{userId}/events:
    get:
      tags:
      - "reserve"
      summary: "get all own events"
      description: ""
      operationId: "getEvents"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"
  /user/{userId}/eventsExpired:        
    get:
      tags:
      - "reserve"
      summary: "get all own events that expired"
      description: ""
      operationId: "getEventsExpired"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"     
  /user/logout:
    post:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /user/{id}:
    get:
      tags:
      - "user"
      summary: "Get user by user id"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        404:
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "string"
      responses:
        404:
          description: "User not found"
          
  /admin/resolveReservation/{reservationId}:
    get:
      tags:
      - "admin"
      summary: "resolve reservation"
      description: ""
      operationId: "resolveReservation"
      produces:
      - "application/json"
      parameters:
      - name: "reservationId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"
          schema:
            $ref: "#/definitions/Notice"
            
  
  /admin/getScheduleByUserId/{userId}:
    get:
      tags:
      - "admin"
      summary: "get schedule specific user by it Id"
      description: ""
      operationId: "getscheduleByUserId"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"
        
        
  /admin/rejectReservation/{reservationId}:
    post:
      tags:
      - "admin"
      summary: "reject reservation"
      description: ""
      operationId: "rejectReservation"
      produces:
      - "application/json"
      parameters:
      - name: "reservationId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input" 
          schema:
            $ref: "#/definitions/Notice"
  
definitions:

  Attribute:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      typeOfAttribute: 
        description: "string or number or Date"
      isRequire:
        type: "boolean"
        
  Reservation:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      author:
        type: "string"
      period: 
        type: "object"
        properties:
          dateStart:
            type: "object"
          dateEnd:
            type: "object"
      status:
        description: "confirmed or created or rejected"
      values:
        type: "object"
        
  Notice:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      id_reservation:
        type: "integer"
        format: "int64"
      type:
        description: "confirmed or created or rejected or resolved"
      status:
        type: "boolean"

  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
  Admin:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
  Schedule:
    type: "object"
    required:
    - "name"
    - "period"
    - "sizeSlot"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      period:
        type: "object"
        description: "into object timestamps Start and End"
      slots: 
        type: "array"
        items:
          type: "number"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
